server.port=8080
spring.emily.captcha.enabled=true
spring.emily.captcha.width=320
spring.emily.captcha.height=160
spring.emily.captcha.char-count=5
spring.emily.captcha.target-count=3
spring.emily.captcha.font-size-min=32
spring.emily.captcha.font-size-max=30
spring.emily.captcha.noise-line-count=6
spring.emily.captcha.noise-point-count=30
spring.emily.captcha.expire-seconds=120
spring.emily.captcha.tolerance=20